"""Add custom_instructions to InterviewSession

Revision ID: 2ec992f4a05f
Revises: 39b6e8b9ea7d
Create Date: 2026-07-10 01:29:41.387010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ec992f4a05f'
down_revision: Union[str, Sequence[str], None] = '39b6e8b9ea7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_sessions', sa.Column('custom_instructions', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_sessions', 'custom_instructions')
    # ### end Alembic commands ###
